### ISSUE TITLE
GitHub月榜：最火的开源项目榜单出炉！

### ISSUE THREAD

**Issue by szwnba** [szwnba/affweb#253]
点击上方框架师，选择"置顶公众号"  
每天推送原创高质量技术干货！

![](https://mmbiz.qpic.cn/sz_mmbiz_jpg/cKjFPH56nJrhysHcRpiavP9ibg7pUbv6icVWZyg977t1q8k42icIK3oY4PlhxEwYJP0xj7umWfmf6Psp0f1JJeSKGw/640?wx_fmt=jpeg)

> GitHub每月热榜是一个极其受欢迎的开源项目排名榜单，它会列出每月获得最多关注的项目，并按照各种语言、框架和领域进行分类。在这里，您不仅可以发现最新的技术趋势和社区动态，还能找到一些超棒的开源项目。浏览每日热榜不仅能让您与业界同步，还能让您的眼界更加开阔，发现更多的技术创新。现在就跟随我一起来看看 GitHub 本月热榜吧！

* * *

"下方为本月 GitHub 热门项目"

* * *

🏷: 131  
作者：pengzhile  
项目语言: Python  
仓库名称: pandora  
当前⭐：11,348  
当前📌：2,049  
新增⭐：709 stars today  
项目地址：https://github.com/pengzhile/pandora  
项目描述：潘多拉，一个让你呼吸顺畅的ChatGPT。Pandora, a ChatGPT that helps you breathe smoothly.  

* * *

🏷: 134  
作者：freeCodeCamp  
项目语言: TypeScript  
仓库名称: freeCodeCamp  
当前⭐：367,907  
当前📌：32,280  
新增⭐：85 stars today  
项目地址：https://github.com/freeCodeCamp/freeCodeCamp  
项目描述：freeCodeCamp.org's open-source codebase and curriculum. Learn to code for free.  

* * *

🏷: 268  
作者：immersive-translate  
项目语言: TypeScript  
仓库名称: immersive-translate  
当前⭐：8,030  
当前📌：412  
新增⭐：139 stars today  
项目地址：https://github.com/immersive-translate/immersive-translate  
项目描述：Immersive Dual Web Page Translation Extension - 沉浸式双语网页翻译扩展  

* * *

🏷: 278  
作者：iperov  
项目语言: Python  
仓库名称: DeepFaceLive  
当前⭐：13,203  
当前📌：1,743  
新增⭐：452 stars today  
项目地址：https://github.com/iperov/DeepFaceLive  
项目描述：Real-time face swap for PC streaming or video calls  

* * *

🏷: 284  
作者：ShishirPatil  
项目语言: Python  
仓库名称: gorilla  
当前⭐：2,103  
当前📌：111  
新增⭐：440 stars today  
项目地址：https://github.com/ShishirPatil/gorilla  
项目描述：Gorilla: An API store for LLMs  

* * *

🏷: 286  
作者：SamurAIGPT  
项目语言: JavaScript  
仓库名称: privateGPT  
当前⭐：970  
当前📌：78  
新增⭐：321 stars today  
项目地址：https://github.com/SamurAIGPT/privateGPT  
项目描述：An app to interact privately with your documents using the power of GPT, 100% privately, no data leaks  

* * *

🏷: 287  
作者：vue-vine  
项目语言: TypeScript  
仓库名称: vue-vine  
当前⭐：463  
当前📌：16  
新增⭐：50 stars today  
项目地址：https://github.com/vue-vine/vue-vine  
项目描述：Another style of writing Vue components.  

* * *

🏷: 288  
作者：Neo-Desktop  
项目语言: C++  
仓库名称: WindowsXPKg  
当前⭐：1,249  
当前📌：130  
新增⭐：640 stars today  
项目地址：https://github.com/Neo-Desktop/WindowsXPKg  
项目描述：Keygen for Windows XP  

* * *

🏷: 297  
作者：MineDojo  
项目语言: Python  
仓库名称: Voyager  
当前⭐：2,314  
当前📌：176  
新增⭐：589 stars today  
项目地址：https://github.com/MineDojo/Voyager  
项目描述：An Open-Ended Embodied Agent with Large Language Models  

* * *

🏷: 298  
作者：sjvasquez  
项目语言: Python  
仓库名称: handwriting-synthesis  
当前⭐：3,017  
当前📌：454  
新增⭐：254 stars today  
项目地址：https://github.com/sjvasquez/handwriting-synthesis  
项目描述：Handwriting Synthesis with RNNs ️  

* * *

🏷: 299  
作者：lucidrains  
项目语言: Python  
仓库名称: soundstorm-pytorch  
当前⭐：622  
当前📌：37  
新增⭐：121 stars today  
项目地址：https://github.com/lucidrains/soundstorm-pytorch  
项目描述：Implementation of SoundStorm, Efficient Parallel Audio Generation from Google Deepmind, in Pytorch  

* * *

🏷: 304  
作者：ClassmateLin  
项目语言: Rust  
仓库名称: dm-ticket  
当前⭐：820  
当前📌：157  
新增⭐：206 stars today  
项目地址：https://github.com/ClassmateLin/dm-ticket  
项目描述：大麦网自动购票, 支持docker一键部署。https://t.me/+2EELgNTYiMYxMTFl  

* * *

🏷: 305  
作者：threestudio-project  
项目语言: Python  
仓库名称: threestudio  
当前⭐：888  
当前📌：55  
新增⭐：30 stars today  
项目地址：https://github.com/threestudio-project/threestudio  
项目描述：A unified framework for 3D content generation.  

* * *

🏷: 306  
作者：OpenBMB  
项目语言: Python  
仓库名称: CPM-Bee  
当前⭐：587  
当前📌：45  
新增⭐：163 stars today  
项目地址：https://github.com/OpenBMB/CPM-Bee  
项目描述：百亿参数的中英文双语基座大模型  

* * *

🏷: 307  
作者：clovaai  
项目语言: Python  
仓库名称: donut  
当前⭐：3,129  
当前📌：240  
新增⭐：551 stars today  
项目地址：https://github.com/clovaai/donut  
项目描述：Official Implementation of OCR-free Document Understanding Transformer (Donut) and Synthetic Document Generator (SynthDoG), ECCV 2022  

* * *

🏷: 308  
作者：PromtEngineer  
项目语言: Python  
仓库名称: localGPT  
当前⭐：462  
当前📌：53  
新增⭐：148 stars today  
项目地址：https://github.com/PromtEngineer/localGPT  
项目描述：Chat with your documents on your local device using GPT models. No data leaves your device and 100% private.  

* * *

🏷: 309  
作者：dabit3  
项目语言: TypeScript  
仓库名称: semantic-search-nextjs-pinecone-langchain-chatgpt  
当前⭐：234  
当前📌：12  
新增⭐：43 stars today  
项目地址：https://github.com/dabit3/semantic-search-nextjs-pinecone-langchain-chatgpt  
项目描述：Embeds text files into vectors, stores them on Pinecone, and enables semantic search using GPT3 and Langchain in a Next.js UI  

* * *

🏷: 310  
作者：WankkoRee  
项目语言: Python  
仓库名称: eaio  
当前⭐：653  
当前📌：7  
新增⭐：128 stars today  
项目地址：https://github.com/WankkoRee/eaio  
项目描述：一个通过将磁盘上所有 Electron 应用中相同文件硬链接到统一位置来减少磁盘占用的解决方案，就像 pnpm 一样。  

* * *

🏷: 311  
作者：jetlinks  
项目语言: Java  
仓库名称: jetlinks-community  
当前⭐：3,946  
当前📌：1,365  
新增⭐：28 stars today  
项目地址：https://github.com/jetlinks/jetlinks-community  
项目描述：JetLinks 基于Java8,Spring Boot 2.x ,WebFlux,Netty,Vert.x,Reactor等开发, 是一个全响应式的企业级物联网平台。支持统一物模型管理,多种设备,多种厂家,统一管理。统一设备连接管理,多协议适配(TCP,MQTT,UDP,CoAP,HTTP等),屏蔽网络编程复杂性,灵活接入不同厂家不同协议等设备。实时数据处理,设备告警,消息通知,数据转发。地理位置,数据可视化等。能帮助你快速建立物联网相关业务系统。  

* * *

🏷: 312  
作者：honghuangdc  
项目语言: TypeScript  
仓库名称: soybean-admin  
当前⭐：3,962  
当前📌：818  
新增⭐：24 stars today  
项目地址：https://github.com/honghuangdc/soybean-admin  
项目描述：A fresh and elegant admin template, based on Vue3,Vite3,TypeScript,NaiveUI and UnoCSS \[一个基于Vue3、Vite3、TypeScript、NaiveUI 和 UnoCSS的清新优雅的中后台模版\]  

* * *

🏷: 313  
作者：mifi  
项目语言: JavaScript  
仓库名称: lossless-cut  
当前⭐：16,985  
当前📌：949  
新增⭐：44 stars today  
项目地址：https://github.com/mifi/lossless-cut  
项目描述：The swiss army knife of lossless video/audio editing  

* * *

🏷: 314  
作者：TencentARC  
项目语言: Python  
仓库名称: GFPGAN  
当前⭐：29,146  
当前📌：4,577  
新增⭐：67 stars today  
项目地址：https://github.com/TencentARC/GFPGAN  
项目描述：GFPGAN aims at developing Practical Algorithms for Real-world Face Restoration.  

* * *

🏷: 315  
作者：facebookresearch  
项目语言: Python  
仓库名称: ImageBind  
当前⭐：6,019  
当前📌：500  
新增⭐：46 stars today  
项目地址：https://github.com/facebookresearch/ImageBind  
项目描述：ImageBind One Embedding Space to Bind Them All  

* * *

🏷: 316  
作者：mengzonefire  
项目语言:  
仓库名称: rapid-upload-userscript  
当前⭐：845  
当前📌：140  
新增⭐：60 stars today  
项目地址：https://github.com/mengzonefire/rapid-upload-userscript  
项目描述：秒传链接提取脚本, 使用typescript + webpack重构  

* * *

🏷: 317  
作者：h2oai  
项目语言: Python  
仓库名称: h2ogpt  
当前⭐：1,600  
当前📌：111  
新增⭐：60 stars today  
项目地址：https://github.com/h2oai/h2ogpt  
项目描述：Come join the movement to make the world's best open source GPT led by H2O.ai - 100% private chat and document search, no data leaks, Apache 2.0  

* * *

"下方为今日随机推荐的C++项目"

* * *

🏷: 205  
作者：filecxx  
项目语言: C++  
仓库名称: FileCentipede  
仓库地址：https://github.com/filecxx/FileCentipede  
项目描述：它界面简洁、下载速度快、支持多协议，还有浏览器插件可用来下载网页中的视频和音频。  

* * *

🏷: 206  
作者：CnTransGroup  
项目语言: Other  
仓库名称: EffectiveModernCppChinese  
仓库地址：https://github.com/CnTransGroup/EffectiveModernCppChinese  
项目描述：教你如何写出正确、高效、可维护的 C++ 代码的书，该项目为中文翻译版本(已完成)。  

* * *

🏷: 209  
作者：iovisor  
项目语言: C++  
仓库名称: bpftrace  
仓库地址：https://github.com/iovisor/bpftrace  
项目描述：该工具基于 eBPF 和 BCC 实现了通过探针机制采集内核和程序运行的信息，然后用图表等方式将信息展示出来，帮助开发者找到隐藏较深的 Bug、安全问题和性能瓶颈。  

* * *

🏷: 210  
作者：ossrs  
项目语言: C++  
仓库名称: srs  
仓库地址：https://github.com/ossrs/srs  
项目描述：高性能的流媒体服务器，支持 RTMP、WebRTC、HLS 和 HTTP-FLV 等协议，常用来构建直播和视频会议的后端服务。  

* * *

🏷: 211  
作者：aseprite  
项目语言: C++  
仓库名称: aseprite  
仓库地址：https://github.com/aseprite/aseprite  
项目描述：一款主要用于像素画和 Sprite 动画的图像编辑软件，它拥有图层、自由手绘模式、阴影墨水、自定义笔刷、轮廓线、宽像素、命令行界面、Lua 脚本等特色功能。该软件虽然专业版收费但并不贵，也可选择免费版但无法保存作品。  

* * *

🏷: 216  
作者：baidu  
项目语言: C++  
仓库名称: bfs  
仓库地址：https://github.com/baidu/bfs  
项目描述：这是一个分布式文件系统，它具有高容错、低延迟、高吞吐等特性，应用于百度的网页数据库、增量索引系统、用户行为分析等系统。  

* * *

🏷: 217  
作者：facebook  
项目语言: C++  
仓库名称: rocksdb  
仓库地址：https://github.com/facebook/rocksdb  
项目描述：该项目是由 Fackbook 数据库团队基于 levelDB 开发，键值均支持二进制流，能够充分利用多核 CPU 获得高性能，并兼容 levelDB 的 API 可谓是青出于蓝而胜于蓝，一些开源数据库底层存储用的就是它。  

* * *

🏷: 222  
作者：official-stockfish  
项目语言: C++  
仓库名称: Stockfish  
仓库地址：https://github.com/official-stockfish/Stockfish  
项目描述：它在众多国际象棋引擎评级列表中均名列前茅，棋艺基本上是吊打职业选手。它不仅可以对战，还支持棋局分析、评估棋艺，帮助国际象棋爱好者提升棋技。虽然这是一个引擎不能单独运行，但是社区提供了丰富的 GUI 软件下载就能用，甚至还可以用来解说国际象棋比赛。  

* * *

🏷: 228  
作者：xbmc  
项目语言: C++  
仓库名称: xbmc  
仓库地址：https://github.com/xbmc/xbmc  
项目描述：这是一个媒体播放器软件，但折腾一下就是家庭媒体娱乐中心。它不仅支持播放本地视频，还能够安装各种插件以及播放网络存储设备(NAS)、投屏、直播、电视、播客等源。能够运行在 Linux、macOS、Windows、Android、iOS 等设备，界面支持中文更多功能等待你的挖掘。  

* * *

🏷: 235  
作者：topjohnwu  
项目语言: C++  
仓库名称: Magisk  
仓库地址：https://github.com/topjohnwu/Magisk  
项目描述：它可以快速、无痛地获得 Android 的超级用户权限，支持 Android 5.0 以上的设备。  

* * *

🏷: 237  
作者：qinguoyi  
项目语言: C++  
仓库名称: TinyWebServer  
仓库地址：https://github.com/qinguoyi/TinyWebServer  
项目描述：该项目不仅可以用来搭建 Web 服务，也适合 C++ 初学者作为网络编程实战项目。作者还写了文章讲解相关代码和原理，帮助初学者更好的掌握网络编程相关知识。  

* * *

🏷: 246  
作者：isocpp  
项目语言: Python  
仓库名称: CppCoreGuidelines  
仓库地址：https://github.com/isocpp/CppCoreGuidelines  
项目描述：一份由 C++ 之父 Bjarne Stroustrup 领导的 C++ 编码指南，目的是为了帮助大家更好地使用现代 C++。这个项目主要讨论的是关于 C++ 编写接口、内存管理、并发等方面的问题，适合有一定 C++ 基础想要进阶的小伙伴。  

* * *

🏷: 248  
作者：rohit-px2  
项目语言: C++  
仓库名称: nvui  
仓库地址：https://github.com/rohit-px2/nvui  
项目描述：它使用起来流畅，动画效果细腻、美观，你可以用 Neovim 和 nvui 自由定制出一个高颜值、最懂你的编辑器。  

* * *

🏷: 250  
作者：Tencent  
项目语言: C++  
仓库名称: GameAISDK  
仓库地址：https://github.com/Tencent/GameAISDK  
项目描述：支持吃鸡类、射击类、MOBA 类等游戏类型。内置多种图像识别算法和 AI 算法，不用抠图完全基于图像识别的 AI 训练和框架。  

* * *

🏷: 254  
作者：ocornut  
项目语言: C++  
仓库名称: imgui  
仓库地址：https://github.com/ocornut/imgui  
项目描述：这是个即时模式的 GUI 框架，控件都需要手绘。优点是更加灵活和轻量，可以快速构建功能简单、体积小的 GUI 程序，但不适合用来实现复杂动画的 GUI 应用，多用于开发游戏内的 GUI 工具。  

* * *

🏷: 261  
作者：M2Team  
项目语言: C++  
仓库名称: NanaZip  
仓库地址：https://github.com/M2Team/NanaZip  
项目描述：基于 7-Zip 的开源压缩工具。包含多种压缩算法和美观的 Win11 风格 UI，同时适配 Win11 右键菜单操作  

* * *

🏷: 264  
作者：google  
项目语言: C++  
仓库名称: filament  
仓库地址：https://github.com/google/filament  
项目描述：能够用来做游戏渲染引擎或者音视频编辑工程，当你需要处理 3D 渲染效果，又不想引入庞大的游戏引擎时，可以考虑使用它尤其是 Android 平台。  

* * *

🏷: 266  
作者：CleverRaven  
项目语言: C++  
仓库名称: Cataclysm-DDA  
仓库地址：https://github.com/CleverRaven/Cataclysm-DDA  
项目描述：在《大灾变：黑暗之日》游戏中没有任何任务，唯一的目标就是活下去。玩家可以通过寻找食物、装备等资源建造避难所，还支持车辆改装、制作物品等特色机制，支持 Windows、Linux、macOS、Android 系统。  

* * *

🏷: 271  
作者：Slackadays  
项目语言: C++  
仓库名称: Clipboard  
仓库地址：https://github.com/Slackadays/Clipboard  
项目描述：一款用 C++ 编写的剪贴板工具，可以在终端的任何地方复制、剪切和粘贴东西，使用起来就像 GUI 一样方便，相见恨晚的命令行工具，适用于 Windows、Linux 和 macOS 操作系统。  

* * *

🏷: 275  
作者：microsoft  
项目语言: C++  
仓库名称: AirSim  
仓库地址：https://github.com/microsoft/AirSim  
项目描述：这是一款微软开源的无人机和汽车的仿真模拟器，支持使用流行的飞行控制器进行软件在环(SIL)仿真，并使用 PX4 进行硬件在环(HIL)模拟，实现物理和视觉上逼真的模拟，可用于试验自动驾驶汽车、计算机视觉和强化学习算法。  

* * *

🏷: 277  
作者：WebKit  
项目语言: Other  
仓库名称: WebKit  
仓库地址：https://github.com/WebKit/WebKit  
项目描述：它被用于开发 macOS 和 iOS 上的 Safari、App Store、Mail 等应用。WebKit 不仅出现在苹果的生态中，其分支 Blink 项目也是 Chromium 的重要组成部分，它又是各大主流浏览器的核心。  

* * *

🏷: 280  
作者：qgis  
项目语言: C++  
仓库名称: QGIS  
仓库地址：https://github.com/qgis/QGIS  
项目描述：该项目采用 C++ 语言编写，GUI 部分使用的是 Qt 库。它提供了 GIS 数据可视化、编辑和分析的功能，支持多种 GIS 数据格式，适用于 Windows、Linux、macOS、BSD 和移动设备。  

* * *

🏷: 281  
作者：doctest  
项目语言: C++  
仓库名称: doctest  
仓库地址：https://github.com/doctest/doctest  
项目描述：这是一款轻量级、快速的 C++ 测试框架，它使用起来十分方便，引入头文件即可使用，而且速度快、编译时间短，支持 C++ 11/14/17/20。  

* * *

🏷: 539  
作者：ChungZH  
项目语言: C++  
仓库名称: notepanda  
仓库地址：https://github.com/ChungZH/notepanda  
项目描述：这是一个用 C++ 和 Qt 开发的记事本项目。支持代码高亮、自定义字体样式，还可以命令行呼出，适合作为学习 Qt 的项目。  

* * *

🏷: 562  
作者：XMuli  
项目语言: C++  
仓库名称: ChineseChess  
仓库地址：https://github.com/XMuli/ChineseChess  
项目描述：该项目是基于 Qt5 开发的中国象棋网络对战平台，支持单机、记时、悔棋、下棋记录、网络对战等功能。  

* * *

数据最后更新时间为：2023-05-31 08:31:29

> 如果您想要更快地了解墨白更新的文章，可以扫描下方的二维码关注我的公众号。请记住，墨白只会发布最新的技术文章，如果您想要了解如何在光速下开发软件，就别错过啦！我们下一篇文章见！

* * *

![](https://mmbiz.qpic.cn/sz_mmbiz_gif/cKjFPH56nJrhysHcRpiavP9ibg7pUbv6icV7urLZibbUEG8U7U2PwjKcUckR7oZiaT3cr2rpKntUNkfMU5Fxich8t7icA/640?wx_fmt=gif)

**Comment by lidaohang** [comment]
mark
