### ISSUE TITLE
ChatGPT 的基本功：13 种 Prompt 用法 - 少数派

### ISSUE THREAD

**Issue by szwnba** [szwnba/affweb#54]
普通人使用ChatGPT重在磨练基本功，我下面提供的这套基本功如果你能融会贯通，对内容生产者们有着魔法级别的帮助，至少提升10倍的生产效率。

所谓ChatGPT的基本功核心是学会设置 Prompt ， Prompt 你可以理解成「提示语」，他的目的是让ChatGPT进入某种对话模式。

在ChatGPT中，prompt 通常指的是一个输入的文本段落或短语，作为生成模型输出的起点或引导。prompt 可以是一个问题、一段文字描述、一段对话或任何形式的文本输入，模型会基于 prompt 所提供的上下文和语义信息，生成相应的输出文本。

设置 prompt 就是设置你与ChatGPT的对话模式，以下我先罗列基本的提示模式

1、解释
----

这种模式下，你输入的内容是让ChatGPT对某个概念或理论进行解释和说明。他的主要作用是对各种概念做定义。

比如：

![](https://cdn.sspai.com/2023/03/01/article/727914cef2e7379778eae4f921e81540?imageView2/2/w/1120/q/90/interlace/1/ignore-error/1)

解释案例

2、类比
----

这种模式下，你需要创造两种比喻或类比的对象或着结构，然后让ChatGPT进行概念的迁移。他的主要作用是让我们「以旧学新」，快速理解一些陌生领域的知识。

比如我延续第 1 种模式下，继续让ChatGPT对「设计模式」做具体的解释：

![](https://cdn.sspai.com/2023/03/01/article/de51ba1dec2cd00e5d051bdfe101649a?imageView2/2/w/1120/q/90/interlace/1/ignore-error/1)

类比案例

然后我让他类比到ChatGPT的使用中，用「罗列」提示让他罗列具体内容：

![](https://cdn.sspai.com/2023/03/01/article/1219817ae58ccf41cea41458620d35c4?imageView2/2/w/1120/q/90/interlace/1/ignore-error/1)

这样就完成了不同领域之间概念的交替，有利于让我们快速理解新领域的知识。

3、罗列
----

这种模式的目的你可以让ChatGPT遍历和列举事物的种类、各种属性和特点等。方便你更了解某类事物，主要价值有：提供灵感、补全认知盲区。

比如上面的第2点的罗列案例，再比如这样：

![](https://cdn.sspai.com/2023/03/01/article/201567a21c84f6d2c688eec2a01fccd7?imageView2/2/w/1120/q/90/interlace/1/ignore-error/1)

罗列案例

但你需要注意，他罗列的很多东西看似不重复，其实里面的一些东西本质还是重复的，所以这就涉及一个人的底层认知和思考能力，这个话题这里暂时不展开。

4、转化
----

这种提示模式里，你可让ChatGPT按照你想要的格式转化内容，有利于把混乱的内容整理成清晰的内容。

**案例1：转化为之前的类比概念呈现方式**

![](https://cdn.sspai.com/2023/03/01/article/bcc2894ff2f2c11da1ba5910a39fe90a?imageView2/2/w/1120/q/90/interlace/1/ignore-error/1)

转化案例1

这个案例就是通过定义、类比以后转化方式。

**案例2：转化为markdown文本呈现格式**

![](https://cdn.sspai.com/2023/03/01/article/c7fba147dc888ad7c7acf5397ce22e14?imageView2/2/w/1120/q/90/interlace/1/ignore-error/1)

转化案例2

直接把具体的文字模板也送给你：

> 将以上4种模式转化为 markdown 的 """markdown {} """ 表格形式，其中的字段为名称、简述、案例

5、限制
----

这种提示模式里，你可以限制ChatGPT不要输出某些东西，有利于他更清晰更准确的呈现内容。

**案例：限制年龄**

![](https://cdn.sspai.com/2023/03/01/article/fab33614321608321a03ec11ff9813b0?imageView2/2/w/1120/q/90/interlace/1/ignore-error/1)

限制案例

你还可以限制各种条件，比如让他必须用什么格式输出、比如让他必须用英文，比如让他不能出现XX或者只能出现XX，**案例2：** 

![](https://cdn.sspai.com/2023/03/01/article/ba02d19c39ddc1de7eac58b132cf2abe?imageView2/2/w/1120/q/90/interlace/1/ignore-error/1)

限制+转化案例2

具体的本文内容也送给你：

> 使用 STAR 原则与下面的格式总结一下这段话：
> 
> """
> 
> 最近几天，因为直播 \+ 兴趣的原因，我在研究用 小报童 来展示如何学习ChatGPT的 prompt、用 徐宿的知识体系读者群来展示东半球最强大的知识体系构建方法，而昨天的展示中主要展示的是关于ChatGPT的 prompt 方面的构建、但由于我对技术领域的各种名词缺乏基本的知识储备，所以后半段的直播有点不理想，但我很快调整状态连夜学习。然后，我在第二天写了一篇相对完善的prompt又利于新手使用的小报童文章。
> 
> """
> 
> 情境(Situation):
> 
> 任务(Task):
> 
> 行动(Action): -||-
> 
> 结果(Result): -||-

6、增改
----

增改的意思是进行增加、删除、修改某些内容。这种提示模式下，你可以让他增加或者改正某些内容。本质是一种微调内容的方法。

**案例：增改markdown内容**

我在上面的第4点第2个案例里让ChatGPT把内容转化成markdown格式：

![](https://cdn.sspai.com/2023/03/01/article/f4942c25326bf4d21c75d88c01c14568?imageView2/2/w/1120/q/90/interlace/1/ignore-error/1)

增改案例1

但是里面有些内容有错误，于是我让他进行增改：

![](https://cdn.sspai.com/2023/03/01/article/2a217cac596e1dc7fad21daaf5c0ffc2?imageView2/2/w/1120/q/90/interlace/1/ignore-error/1)

增改案例2

你还可以对他继续操作，比如让他增加序号，或者增加具体模式的案例，都可以。

7、对比
----

这种提示模式下，你可以让ChatGPT比较两个或多个事物之间的相似性和差异性。有利于你分析问题，思考利弊。

**案例1：** 

![](https://cdn.sspai.com/2023/03/01/article/632bcafbc611aacfe9cd6f2e8e1c10ef?imageView2/2/w/1120/q/90/interlace/1/ignore-error/1)

对比案例1

**案例2：** 

![](https://cdn.sspai.com/2023/03/01/article/10b4d4b6bdf6d6b5c78deb7d43bb0503?imageView2/2/w/1120/q/90/interlace/1/ignore-error/1)

对比案例2

8、分类
----

这种提示模式下，你可以让ChatGPT按照一定标准或特点对事物进行分类，价值是更好的分析事物和记忆。

**案例：** 

![](https://cdn.sspai.com/2023/03/01/article/ccf8a86439e5ea678cbeb106ba86aa79?imageView2/2/w/1120/q/90/interlace/1/ignore-error/1)

分类案例1

9、翻译
----

翻译的其实也是转化的一种，只不过由于人类对语言了解需求过于庞大，我单独把他拿出来作为特定研究。

翻译就是让ChatGPT将不同的语言或术语进行翻译和转换，在上面的第4点转化中你已经见识过一些案例，我这里直接让他充当一个真正的语言翻译：

![](https://cdn.sspai.com/2023/03/01/article/4a94d0a414b3b40b526ced807e129170?imageView2/2/w/1120/q/90/interlace/1/ignore-error/1)

翻译案例1

10、推理
-----

这种提示模式下，你可以让ChatGPT观察和推断出未知的事实或逻辑关系，他的价值在于提供更完善的解决方案和灵感。

**案例：** 

![](https://cdn.sspai.com/2023/03/01/article/30716e7c5abf700fb737774917705b94?imageView2/2/w/1120/q/90/interlace/1/ignore-error/1)

推理案例1

11、归纳
-----

你可以把归纳理解成做复盘和总结，这种提示模式下ChatGPT可以从特定的例子或事实中归纳出一般规律或结论，可以让你看清楚一些事情的本质（也考验你的判断力）。

![](https://cdn.sspai.com/2023/03/01/article/47251179205e82fc5673b45eb8d27022?imageView2/2/w/1120/q/90/interlace/1/ignore-error/1)

归纳案例

12、模拟
-----

在这个提示模式下，你可以让ChatGPT模拟某个过程或现象。这个提示的价值是可以让你快速掌握某些技能。

**案例：** 

![](https://cdn.sspai.com/2023/03/01/article/b44fb56fe2610912358f60da2a4d3458?imageView2/2/w/1120/q/90/interlace/1/ignore-error/1)

模拟案例

13、演员
-----

在这个提示模式下，你可以让ChatGPT充当各种角色。这个提示模式的价值是可以让你和他的对话更聚焦，更专业，提高获取信息的效率。

**案例：** 

![](https://cdn.sspai.com/2023/03/01/article/bed341e5f5b50c8eb4d5f3d178a29919?imageView2/2/w/1120/q/90/interlace/1/ignore-error/1)

演员案例

如上的所有提示模式都可以互相组合利用，把他们两两组合或者三三组合会衍化出256种不同的使用方法，足够你应对大部分信息获取和利用需求。

还有一些其他的模式，我还在研究，后续继续补充。

既然说到这里，既然想要用好ChatGPT提升你10~100倍的生产力，你必须深刻理解我在上面这篇文章中说的那些prompt模式，那么如何深刻理解呢？

最快的方法就2个：

1.  看案例总结
2.  直接用来下场做事

我这里直接给你做一个案例，是一篇关于《「2023年洗衣机购买指南」：如何省钱又选到好用的洗衣机？》的案例。

### 第1步：

![](https://cdn.sspai.com/2023/03/01/article/2ffbcd7ec9d8a1a5830f63ddf027050f?imageView2/2/w/1120/q/90/interlace/1/ignore-error/1)

### 第2步：

![](https://cdn.sspai.com/2023/03/01/article/ace2376365da390d32c7bc193beaacb8?imageView2/2/w/1120/q/90/interlace/1/ignore-error/1)

### 第3步：

![](https://cdn.sspai.com/2023/03/01/article/b34ea7419a7f592e5f1f3bc358ae233d?imageView2/2/w/1120/q/90/interlace/1/ignore-error/1)

### 第4步：

![](https://cdn.sspai.com/2023/03/01/article/b488cfaef39bac3bdcf0f015395c0a64?imageView2/2/w/1120/q/90/interlace/1/ignore-error/1)

### 第5步：

![](https://cdn.sspai.com/2023/03/01/article/bb33d96f745d8a978f70165a75d7d1ad?imageView2/2/w/1120/q/90/interlace/1/ignore-error/1)

### 第6步：

![](https://cdn.sspai.com/2023/03/01/article/455dca4c78ffaeae6f30a0194ba76001?imageView2/2/w/1120/q/90/interlace/1/ignore-error/1)

### 第7步：

![](https://cdn.sspai.com/2023/03/01/article/02a45f95919f313ec45ea045b336bacb?imageView2/2/w/1120/q/90/interlace/1/ignore-error/1)

### 第8步：

![](https://cdn.sspai.com/2023/03/01/article/50f92958f1b1553b864d328b974edadc?imageView2/2/w/1120/q/40/interlace/1/ignore-error/1)

### 第9步：

![](https://cdn.sspai.com/2023/03/01/article/24ae164dfa776e6e123d6ca4417fd615?imageView2/2/w/1120/q/40/interlace/1/ignore-error/1)

成品文章一览
------

> ![](https://cdn.sspai.com/2023/03/01/article/6d7cfc4ebe2d56f792ea9c1395a9cfb4?imageView2/2/w/1120/q/40/interlace/1/ignore-error/1)
> 
> 在现代生活中，洗衣机已经成为了不可或缺的家用电器。然而，随着消费者需求的不断提升，市场上涌现出各式各样的洗衣机，让消费者难以选择。
> 
> 很多消费者在购买洗衣机时都会遇到这样的问题：到底要购买哪种类型的洗衣机才能够满足自己的需求？全自动还是半自动？前置式还是上置式？如何根据自己的预算和需求选择最适合自己的洗衣机？
> 
> 这一问题的出现，主要是因为市场上存在太多类型的洗衣机，每一种类型都有各自的特点和适用场景，因此消费者在选择时往往会感到困惑。此外，消费者对于洗衣机的了解也相对较少，导致他们很难做出最明智的决策。
> 
> 在这样的情况下，消费者需要一个能够帮助他们做出最好选择的指南。本文将提供一份详尽的指南，帮助消费者了解不同类型的洗衣机的优缺点，以及如何根据自己的需求和预算做出最明智的选择。同时，我们还会提供一些洗衣机的购买建议和维护技巧，以确保消费者购买到的洗衣机能够发挥最佳的效果，服务更加便捷。
> 
> 当你考虑购买一台洗衣机时，应该先考虑你的需求和预算。洗衣机有多种类型，包括全自动洗衣机、半自动洗衣机、前置式洗衣机、上置式洗衣机等。每种类型的洗衣机都有其优缺点，因此在选择时要考虑以下因素：
> 
> 使用频率和衣物量：如果你家里的衣物量较大，或者需要频繁地洗衣服，全自动洗衣机可能更适合你。半自动洗衣机虽然价格更便宜，但需要更多的人工操作。
> 
> 空间大小：如果你家里的空间比较小，可以考虑选择上置式洗衣机。如果有足够的空间，则可以考虑前置式洗衣机。
> 
> 预算：不同类型的洗衣机价格不同，因此你需要根据自己的预算做出选择。在购买时，不要只看价格，还要考虑机器的性能和使用寿命。
> 
> 综上所述，选择最适合自己的洗衣机需要综合考虑自己的需求和预算，了解不同类型洗衣机的优缺点，并根据自己的实际情况做出最佳的选择。在选择后，还需要按照洗衣机的使用说明正确使用，并保持其干净和维护，以确保其长时间稳定运行。
> 
> 那么接下来我推荐一些综合性能不错的洗衣机，它们的价格在1000~5000元之间，可以满足大部分家庭的需求。
> 
> ![](https://cdn.sspai.com/2023/03/01/article/533f9b14963933abc0eea6725a77ad23?imageView2/2/w/1120/q/40/interlace/1/ignore-error/1)
> 
> 小天鹅（Little Swan） TG70-Y10603：价格在2000元左右，具有自动称重、自动泡洗、自动排水等功能。使用简单，耗电量较低，适合小家庭使用。
> 
> 海尔（Haier） XQG80-KBM1228：价格在3000元左右，具有双缸设计，同时可洗衣服和脱水，适合需要频繁洗衣服的家庭使用。除此之外，还具有自动称重、自动泡洗等功能。
> 
> 美的（Midea） XQG70-1014：价格在4000元左右，具有噪音小、节能省电、抗皱护理、防霉护理等多项功能。适合注重洗涤效果的家庭使用。
> 
> 三洋（Sanyo） ASW-1000XT：价格在5000元左右，拥有大容量、高速旋转、自动称重、防过流、自动出水等功能。适合家庭衣物量较大的用户。
> 
> 综上所述，选择洗衣机需要根据自己的需求和预算进行选择。以上4款洗衣机都拥有各自的特点和优势，消费者可以根据自己的实际情况进行选择。无论选择哪款洗衣机，使用时一定要按照说明书正确使用，避免损坏机器或者出现安全问题。
> 
> 现在我们总结一下，如何选择一款适合自己的洗衣机。不同的经济条件和用途会对选择洗衣机产生不同的影响。
> 
> 对于经济条件较为宽裕的家庭，可以选择价格较高的洗衣机，这些洗衣机往往具有更加完善的功能和更高的耐久性，可以更好地满足家庭的需要。例如，如果家庭成员较多或者衣物种类繁多，建议选择大容量、多功能的洗衣机，例如三洋ASW-1000XT。
> 
> 对于经济条件相对较为有限的家庭，可以选择价格更为亲民的洗衣机，这些洗衣机虽然功能不如高端洗衣机丰富，但在洗涤效果和易用性方面也能够满足基本需求。例如，如果家庭人口较少且生活比较简单，可以选择价格适中的小天鹅TG70-Y10603洗衣机。
> 
> 另外，对于需要经常洗涤衣物的家庭，推荐选择具有双缸设计的洗衣机，例如海尔XQG80-KBM1228。这种洗衣机能够同时完成洗涤和脱水的工作，节省了洗衣服的时间，特别适合需要频繁洗衣服的家庭使用。
> 
> 总之，选择一款适合自己的洗衣机需要考虑到家庭的经济条件和实际需求，根据自己的情况进行选择，才能够买到最适合自己的洗衣机。
> 
> 谢谢大家阅读这篇有关于洗衣机的文章。如果你对我们提供的信息有所启发或者有任何问题和意见，欢迎在下方留言。同时，如果你想了解更多关于家电选购和使用的信息，可以关注我们的微信公众号，我们会不定期地为大家带来更多有趣、实用的内容。

有个思考题，请问我上面整体的案例中用了之前基本功中的几种模式？

我是徐宿，这篇内容希望对你高效利用ChatGPT有所帮助。

**Comment by Bahxo** [comment]
好
